export const roles = {
  owner: [
    "user:read",
    "user:hard_delete",
    "user:soft_delete",
    "user:recover",
    "roles:assign_admin",
    "roles:assign_user",
    "user:file:read",
    "user:file:write",
    "user:file:delete",
    "user:logout",
    "file:read",
    "file:write",
    "file:delete",
    "file:upload",
  ],
  admin: [
    "user:read",
    "user:soft_delete",
    "user:recover",
    "roles:assign_user",
    "user:file:read",
    "user:logout",
    "file:read",
    "file:write",
    "file:delete",
    "file:upload",
  ],
  user: ["file:read", "file:write", "file:delete", "file:upload"],
  viewer: ["file:read"],
};
